"""Render the authoritative YAML control library as a Markdown catalog."""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "controls.yaml"
OUTPUT = ROOT / "docs" / "control-catalog.md"

DOMAIN_TITLES = {
    "administrative_governance": "Administrative Governance",
    "technical_security": "Technical Security",
    "data_privacy": "Data and Privacy",
    "lifecycle": "Lifecycle",
    "agentic_ai": "Agentic AI",
    "monitoring_operations": "Monitoring and Operations",
    "vendor_supply_chain": "Vendor and Supply Chain",
}


def _display(value: str) -> str:
    return str(value).strip()


def render_catalog(library: dict) -> str:
    metadata = library["library"]
    controls = library["controls"]
    lines = [
        "<!-- Generated from data/controls.yaml. Do not edit this file directly. -->",
        "# AI Governance Control Catalog",
        "",
        "This is the human-readable view of the authoritative "
        "[`data/controls.yaml`](../data/controls.yaml) control library. Changes must be "
        "made in the YAML source and regenerated with "
        "`python scripts/render_control_catalog.py`.",
        "",
        f"- **Library:** {_display(metadata['name'])}",
        f"- **Library version:** `{_display(metadata['version'])}`",
        f"- **Schema version:** `{_display(library['schema_version'])}`",
        f"- **Status:** `{_display(metadata['status'])}`",
        f"- **Controls:** {len(controls)}",
        "",
        "## Contents",
        "",
    ]

    for domain, title in DOMAIN_TITLES.items():
        count = sum(control["domain"] == domain for control in controls)
        anchor = title.lower().replace(" ", "-")
        lines.append(f"- [{title}](#{anchor}) ({count})")

    for domain, title in DOMAIN_TITLES.items():
        domain_controls = [control for control in controls if control["domain"] == domain]
        lines.extend(["", f"## {title}", ""])
        for control in domain_controls:
            evidence = ", ".join(_display(item) for item in control["evidence_examples"])
            references = ", ".join(f"`{_display(item)}`" for item in control["references"])
            lines.extend(
                [
                    f"### {control['control_id']}: {_display(control['title'])}",
                    "",
                    f"**Layer:** `{_display(control['layer'])}`",
                    "",
                    f"**Objective:** {_display(control['objective'])}",
                    "",
                    f"**Requirement:** {_display(control['requirement'])}",
                    "",
                    f"**Applicability:** {_display(control['applicability'])}",
                    "",
                    f"**Evidence examples:** {evidence}",
                    "",
                    f"**Implementation notes:** {_display(control['implementation_notes'])}",
                    "",
                    f"**References:** {references}",
                    "",
                ]
            )

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit unsuccessfully when the generated catalog is missing or stale.",
    )
    args = parser.parse_args()

    with SOURCE.open(encoding="utf-8") as stream:
        expected = render_catalog(yaml.safe_load(stream))

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"{OUTPUT.relative_to(ROOT)} is not synchronized with {SOURCE.relative_to(ROOT)}")
            return 1
        return 0

    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Rendered {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
